name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: setup requests
      run: |
        pip install requests
      
    - name: Checkin
      run: |
        python ./main.py 

env: 
  #设置secrets的环境变量
    EMAIL: ${{ secrets.EMAIL }}
    BASE_URL: ${{ secrets.BASE_URL }}
    PASSWORD: ${{ secrets.PASSWORD }}
    SCKEY: ${{ secrets.SCKEY }}
